// AUTO-GENERATED by `mcp__supabase__generate_typescript_types`. Do not edit
// by hand — re-run the generator after schema changes.
//
// EXCEPTION: create_capsule_with_owner's Args (p_contribution_lock_at,
// p_description, p_group_id, p_contribution_start_at) need `| null`
// hand-restored after every regeneration — the generator can't see that this
// plpgsql function accepts NULL for them (Postgres function parameters carry
// no nullability metadata the way column types do; see
// supabase/migrations/20260711160000_atomic_capsule_create.sql and
// supabase/migrations/20260716120000_capsule_start_date.sql, no STRICT
// modifier, all four genuinely accept null). CreateScreen.tsx and
// OnboardingScreen.tsx both pass null through p_contribution_lock_at/
// p_description/p_group_id; CreateScreen.tsx also passes null through
// p_contribution_start_at when no Start Date is set.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      blocked_users: {
        Row: {
          blocked_id: string
          blocker_id: string
          created_at: string
        }
        Insert: {
          blocked_id: string
          blocker_id: string
          created_at?: string
        }
        Update: {
          blocked_id?: string
          blocker_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "blocked_users_blocked_id_fkey"
            columns: ["blocked_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "blocked_users_blocker_id_fkey"
            columns: ["blocker_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      capsule_members: {
        Row: {
          archived_at: string | null
          capsule_id: string
          checkin_at: string | null
          checkin_lat: number | null
          checkin_lng: number | null
          contribution_nudge_1d_sent_at: string | null
          contribution_nudge_3d_sent_at: string | null
          contribution_nudge_7d_sent_at: string | null
          id: string
          invited_at: string
          joined_at: string | null
          role: string
          user_id: string
        }
        Insert: {
          archived_at?: string | null
          capsule_id: string
          checkin_at?: string | null
          checkin_lat?: number | null
          checkin_lng?: number | null
          contribution_nudge_1d_sent_at?: string | null
          contribution_nudge_3d_sent_at?: string | null
          contribution_nudge_7d_sent_at?: string | null
          id?: string
          invited_at?: string
          joined_at?: string | null
          role: string
          user_id: string
        }
        Update: {
          archived_at?: string | null
          capsule_id?: string
          checkin_at?: string | null
          checkin_lat?: number | null
          checkin_lng?: number | null
          contribution_nudge_1d_sent_at?: string | null
          contribution_nudge_3d_sent_at?: string | null
          contribution_nudge_7d_sent_at?: string | null
          id?: string
          invited_at?: string
          joined_at?: string | null
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "capsule_members_capsule_id_fkey"
            columns: ["capsule_id"]
            isOneToOne: false
            referencedRelation: "capsules"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "capsule_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      capsules: {
        Row: {
          archived_at: string | null
          contribution_lock_at: string | null
          contribution_start_at: string | null
          contribution_start_notified_at: string | null
          created_at: string
          description: string | null
          group_id: string | null
          id: string
          occasion: string
          owner_id: string
          owner_preview_locked: boolean
          proximity_radius_m: number
          status: string
          superlative_closing_soon_sent_at: string | null
          superlative_voting_closes_at: string | null
          superlative_voting_finalized_at: string | null
          superlative_voting_hours: number
          title: string
          unlock_at: string
          unlock_mode: string
          unlock_reminder_10m_sent_at: string | null
          unlock_reminder_1d_sent_at: string | null
          unlock_reminder_1h_sent_at: string | null
          unlocked_at: string | null
          visibility: string
        }
        Insert: {
          archived_at?: string | null
          contribution_lock_at?: string | null
          contribution_start_at?: string | null
          contribution_start_notified_at?: string | null
          created_at?: string
          description?: string | null
          group_id?: string | null
          id?: string
          occasion?: string
          owner_id: string
          owner_preview_locked?: boolean
          proximity_radius_m?: number
          status?: string
          superlative_closing_soon_sent_at?: string | null
          superlative_voting_closes_at?: string | null
          superlative_voting_finalized_at?: string | null
          superlative_voting_hours?: number
          title: string
          unlock_at: string
          unlock_mode?: string
          unlock_reminder_10m_sent_at?: string | null
          unlock_reminder_1d_sent_at?: string | null
          unlock_reminder_1h_sent_at?: string | null
          unlocked_at?: string | null
          visibility?: string
        }
        Update: {
          archived_at?: string | null
          contribution_lock_at?: string | null
          contribution_start_at?: string | null
          contribution_start_notified_at?: string | null
          created_at?: string
          description?: string | null
          group_id?: string | null
          id?: string
          occasion?: string
          owner_id?: string
          owner_preview_locked?: boolean
          proximity_radius_m?: number
          status?: string
          superlative_closing_soon_sent_at?: string | null
          superlative_voting_closes_at?: string | null
          superlative_voting_finalized_at?: string | null
          superlative_voting_hours?: number
          title?: string
          unlock_at?: string
          unlock_mode?: string
          unlock_reminder_10m_sent_at?: string | null
          unlock_reminder_1d_sent_at?: string | null
          unlock_reminder_1h_sent_at?: string | null
          unlocked_at?: string | null
          visibility?: string
        }
        Relationships: [
          {
            foreignKeyName: "capsules_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "capsules_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      content_reports: {
        Row: {
          capsule_id: string | null
          created_at: string
          details: string | null
          id: string
          reason: string
          reported_media_id: string | null
          reported_user_id: string | null
          reporter_id: string
          status: string
          target_type: string
        }
        Insert: {
          capsule_id?: string | null
          created_at?: string
          details?: string | null
          id?: string
          reason: string
          reported_media_id?: string | null
          reported_user_id?: string | null
          reporter_id: string
          status?: string
          target_type: string
        }
        Update: {
          capsule_id?: string | null
          created_at?: string
          details?: string | null
          id?: string
          reason?: string
          reported_media_id?: string | null
          reported_user_id?: string | null
          reporter_id?: string
          status?: string
          target_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "content_reports_capsule_id_fkey"
            columns: ["capsule_id"]
            isOneToOne: false
            referencedRelation: "capsules"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "content_reports_reported_media_id_fkey"
            columns: ["reported_media_id"]
            isOneToOne: false
            referencedRelation: "media"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "content_reports_reported_user_id_fkey"
            columns: ["reported_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "content_reports_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      contribution_activity_pending: {
        Row: {
          capsule_id: string
          last_upload_at: string
          photo_count: number
          uploader_id: string
        }
        Insert: {
          capsule_id: string
          last_upload_at?: string
          photo_count?: number
          uploader_id: string
        }
        Update: {
          capsule_id?: string
          last_upload_at?: string
          photo_count?: number
          uploader_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "contribution_activity_pending_capsule_id_fkey"
            columns: ["capsule_id"]
            isOneToOne: false
            referencedRelation: "capsules"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contribution_activity_pending_uploader_id_fkey"
            columns: ["uploader_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      friendships: {
        Row: {
          addressee_id: string
          created_at: string
          id: string
          requester_id: string
          responded_at: string | null
          status: string
        }
        Insert: {
          addressee_id: string
          created_at?: string
          id?: string
          requester_id: string
          responded_at?: string | null
          status?: string
        }
        Update: {
          addressee_id?: string
          created_at?: string
          id?: string
          requester_id?: string
          responded_at?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "friendships_addressee_id_fkey"
            columns: ["addressee_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "friendships_requester_id_fkey"
            columns: ["requester_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      group_members: {
        Row: {
          group_id: string
          id: string
          joined_at: string
          user_id: string
        }
        Insert: {
          group_id: string
          id?: string
          joined_at?: string
          user_id: string
        }
        Update: {
          group_id?: string
          id?: string
          joined_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "group_members_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "group_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      groups: {
        Row: {
          anchor_day: number | null
          anchor_day_of_month: number | null
          anchor_hour: number | null
          anchor_minute: number | null
          anchor_month: number | null
          anchor_weekday: number | null
          created_at: string
          created_by: string
          id: string
          last_capsule_at: string | null
          name: string
          next_capsule_at: string | null
          next_reminder_sent_at: string | null
          recurrence_interval: string
          recurrence_paused_at: string | null
          reminder_lead_hours: number | null
          unlock_duration_hours: number
        }
        Insert: {
          anchor_day?: number | null
          anchor_day_of_month?: number | null
          anchor_hour?: number | null
          anchor_minute?: number | null
          anchor_month?: number | null
          anchor_weekday?: number | null
          created_at?: string
          created_by: string
          id?: string
          last_capsule_at?: string | null
          name: string
          next_capsule_at?: string | null
          next_reminder_sent_at?: string | null
          recurrence_interval?: string
          recurrence_paused_at?: string | null
          reminder_lead_hours?: number | null
          unlock_duration_hours?: number
        }
        Update: {
          anchor_day?: number | null
          anchor_day_of_month?: number | null
          anchor_hour?: number | null
          anchor_minute?: number | null
          anchor_month?: number | null
          anchor_weekday?: number | null
          created_at?: string
          created_by?: string
          id?: string
          last_capsule_at?: string | null
          name?: string
          next_capsule_at?: string | null
          next_reminder_sent_at?: string | null
          recurrence_interval?: string
          recurrence_paused_at?: string | null
          reminder_lead_hours?: number | null
          unlock_duration_hours?: number
        }
        Relationships: [
          {
            foreignKeyName: "groups_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      media: {
        Row: {
          alt_storage_key: string | null
          capsule_id: string
          caption: string | null
          id: string
          is_flagged: boolean
          media_type: string
          size_bytes: number
          storage_key: string
          thumbnail_key: string | null
          uploaded_at: string
          uploader_id: string | null
        }
        Insert: {
          alt_storage_key?: string | null
          capsule_id: string
          caption?: string | null
          id?: string
          is_flagged?: boolean
          media_type: string
          size_bytes: number
          storage_key: string
          thumbnail_key?: string | null
          uploaded_at?: string
          uploader_id?: string | null
        }
        Update: {
          alt_storage_key?: string | null
          capsule_id?: string
          caption?: string | null
          id?: string
          is_flagged?: boolean
          media_type?: string
          size_bytes?: number
          storage_key?: string
          thumbnail_key?: string | null
          uploaded_at?: string
          uploader_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "media_capsule_id_fkey"
            columns: ["capsule_id"]
            isOneToOne: false
            referencedRelation: "capsules"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "media_uploader_id_fkey"
            columns: ["uploader_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          actor_id: string | null
          capsule_id: string | null
          count: number | null
          group_id: string | null
          id: string
          pushed_at: string | null
          read_at: string | null
          sent_at: string
          type: string
          user_id: string
        }
        Insert: {
          actor_id?: string | null
          capsule_id?: string | null
          count?: number | null
          group_id?: string | null
          id?: string
          pushed_at?: string | null
          read_at?: string | null
          sent_at?: string
          type: string
          user_id: string
        }
        Update: {
          actor_id?: string | null
          capsule_id?: string | null
          count?: number | null
          group_id?: string | null
          id?: string
          pushed_at?: string | null
          read_at?: string | null
          sent_at?: string
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_capsule_id_fkey"
            columns: ["capsule_id"]
            isOneToOne: false
            referencedRelation: "capsules"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      reactions: {
        Row: {
          created_at: string
          emoji: string
          id: string
          media_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          emoji: string
          id?: string
          media_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          emoji?: string
          id?: string
          media_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reactions_media_id_fkey"
            columns: ["media_id"]
            isOneToOne: false
            referencedRelation: "media"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      superlative_categories: {
        Row: {
          capsule_id: string
          created_at: string
          id: string
          is_default: boolean
          label: string
          promoted_at: string | null
          status: string
          suggested_by: string
          target_type: string
        }
        Insert: {
          capsule_id: string
          created_at?: string
          id?: string
          is_default?: boolean
          label: string
          promoted_at?: string | null
          status?: string
          suggested_by: string
          target_type: string
        }
        Update: {
          capsule_id?: string
          created_at?: string
          id?: string
          is_default?: boolean
          label?: string
          promoted_at?: string | null
          status?: string
          suggested_by?: string
          target_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "superlative_categories_capsule_id_fkey"
            columns: ["capsule_id"]
            isOneToOne: false
            referencedRelation: "capsules"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "superlative_categories_suggested_by_fkey"
            columns: ["suggested_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      superlative_upvotes: {
        Row: {
          category_id: string
          created_at: string
          user_id: string
        }
        Insert: {
          category_id: string
          created_at?: string
          user_id: string
        }
        Update: {
          category_id?: string
          created_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "superlative_upvotes_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "superlative_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "superlative_upvotes_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      superlative_votes: {
        Row: {
          category_id: string
          created_at: string
          target_media_id: string | null
          target_user_id: string | null
          updated_at: string
          voter_id: string
        }
        Insert: {
          category_id: string
          created_at?: string
          target_media_id?: string | null
          target_user_id?: string | null
          updated_at?: string
          voter_id: string
        }
        Update: {
          category_id?: string
          created_at?: string
          target_media_id?: string | null
          target_user_id?: string | null
          updated_at?: string
          voter_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "superlative_votes_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "superlative_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "superlative_votes_target_media_id_fkey"
            columns: ["target_media_id"]
            isOneToOne: false
            referencedRelation: "media"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "superlative_votes_target_user_id_fkey"
            columns: ["target_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "superlative_votes_voter_id_fkey"
            columns: ["voter_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      superlative_winners: {
        Row: {
          category_id: string
          determined_at: string
          id: string
          target_media_id: string | null
          target_user_id: string | null
          vote_count: number
        }
        Insert: {
          category_id: string
          determined_at?: string
          id?: string
          target_media_id?: string | null
          target_user_id?: string | null
          vote_count: number
        }
        Update: {
          category_id?: string
          determined_at?: string
          id?: string
          target_media_id?: string | null
          target_user_id?: string | null
          vote_count?: number
        }
        Relationships: [
          {
            foreignKeyName: "superlative_winners_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "superlative_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "superlative_winners_target_media_id_fkey"
            columns: ["target_media_id"]
            isOneToOne: false
            referencedRelation: "media"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "superlative_winners_target_user_id_fkey"
            columns: ["target_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          accent_color: string
          auth_provider: string
          avatar_url: string | null
          bio: string | null
          created_at: string
          display_name: string
          email: string | null
          home_layout: string
          id: string
          onboarded_at: string | null
          phone: string | null
          push_token: string | null
          subscription_tier: string
        }
        Insert: {
          accent_color?: string
          auth_provider?: string
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          display_name: string
          email?: string | null
          home_layout?: string
          id: string
          onboarded_at?: string | null
          phone?: string | null
          push_token?: string | null
          subscription_tier?: string
        }
        Update: {
          accent_color?: string
          auth_provider?: string
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          display_name?: string
          email?: string | null
          home_layout?: string
          id?: string
          onboarded_at?: string | null
          phone?: string | null
          push_token?: string | null
          subscription_tier?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      _haversine_m: {
        Args: { lat1: number; lat2: number; lng1: number; lng2: number }
        Returns: number
      }
      _superlative_target_valid: {
        Args: {
          p_category_id: string
          p_target_media_id: string
          p_target_user_id: string
        }
        Returns: boolean
      }
      can_insert_capsule_member: {
        Args: { p_capsule_id: string; p_user_id: string }
        Returns: boolean
      }
      capsule_join_preview: {
        Args: { p_capsule_id: string }
        Returns: {
          already_member: boolean
          id: string
          member_count: number
          owner_avatar: string
          owner_name: string
          title: string
        }[]
      }
      capsule_media_count: { Args: { p_capsule_id: string }; Returns: number }
      check_cron_secret: { Args: { provided: string }; Returns: boolean }
      check_in: {
        Args: { p_capsule_id: string; p_lat: number; p_lng: number }
        Returns: Json
      }
      claim_contribution_nudge_tier: {
        Args: { p_tier: string }
        Returns: {
          capsule_id: string
          capsule_title: string
          effective_deadline: string
          user_id: string
        }[]
      }
      close_superlative_windows: { Args: never; Returns: undefined }
      create_capsule_with_owner: {
        Args: {
          p_contribution_lock_at: string | null
          p_contribution_start_at?: string | null
          p_description: string | null
          p_group_id?: string | null
          p_occasion: string
          p_owner_preview_locked: boolean
          p_superlative_voting_hours: number
          p_title: string
          p_unlock_at: string
          p_unlock_mode: string
          p_visibility?: string
        }
        Returns: string
      }
      delete_capsule_with_storage: {
        Args: { p_capsule_id: string }
        Returns: undefined
      }
      delete_my_account: {
        Args: { p_delete_contributions?: boolean }
        Returns: undefined
      }
      dispatch_superlative_closing_soon: { Args: never; Returns: undefined }
      finalize_capsule_superlatives: {
        Args: { p_capsule_id: string }
        Returns: undefined
      }
      get_my_capsule_ids: { Args: never; Returns: string[] }
      get_my_group_ids: { Args: never; Returns: string[] }
      is_group_creator: { Args: { p_group_id: string }; Returns: boolean }
      set_capsule_archived: {
        Args: { p_archived: boolean; p_capsule_id: string }
        Returns: undefined
      }
      set_default_superlatives: {
        Args: { p_awards: Json; p_capsule_id: string }
        Returns: undefined
      }
      tally_superlatives: {
        Args: { p_capsule_id: string }
        Returns: {
          category_id: string
          target_media_id: string
          target_user_id: string
          vote_count: number
        }[]
      }
      top_contributors: {
        Args: { p_capsule_id: string }
        Returns: {
          display_name: string
          photo_count: number
          user_id: string
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
