// AUTO-GENERATED by `mcp__supabase__generate_typescript_types`. Do not edit
// by hand — re-run the generator after schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      capsule_members: {
        Row: {
          capsule_id: string
          checkin_at: string | null
          checkin_lat: number | null
          checkin_lng: number | null
          id: string
          invited_at: string
          joined_at: string | null
          role: string
          user_id: string
        }
        Insert: {
          capsule_id: string
          checkin_at?: string | null
          checkin_lat?: number | null
          checkin_lng?: number | null
          id?: string
          invited_at?: string
          joined_at?: string | null
          role: string
          user_id: string
        }
        Update: {
          capsule_id?: string
          checkin_at?: string | null
          checkin_lat?: number | null
          checkin_lng?: number | null
          id?: string
          invited_at?: string
          joined_at?: string | null
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "capsule_members_capsule_id_fkey"
            columns: ["capsule_id"]
            isOneToOne: false
            referencedRelation: "capsules"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "capsule_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      capsules: {
        Row: {
          archived_at: string | null
          contribution_lock_at: string | null
          created_at: string
          description: string | null
          id: string
          owner_id: string
          proximity_radius_m: number
          status: string
          superlative_closing_soon_sent_at: string | null
          superlative_voting_closes_at: string | null
          superlative_voting_finalized_at: string | null
          superlative_voting_hours: number
          title: string
          unlock_at: string
          unlock_mode: string
          unlocked_at: string | null
          visibility: string
        }
        Insert: {
          archived_at?: string | null
          contribution_lock_at?: string | null
          created_at?: string
          description?: string | null
          id?: string
          owner_id: string
          proximity_radius_m?: number
          status?: string
          superlative_closing_soon_sent_at?: string | null
          superlative_voting_closes_at?: string | null
          superlative_voting_finalized_at?: string | null
          superlative_voting_hours?: number
          title: string
          unlock_at: string
          unlock_mode?: string
          unlocked_at?: string | null
          visibility?: string
        }
        Update: {
          archived_at?: string | null
          contribution_lock_at?: string | null
          created_at?: string
          description?: string | null
          id?: string
          owner_id?: string
          proximity_radius_m?: number
          status?: string
          superlative_closing_soon_sent_at?: string | null
          superlative_voting_closes_at?: string | null
          superlative_voting_finalized_at?: string | null
          superlative_voting_hours?: number
          title?: string
          unlock_at?: string
          unlock_mode?: string
          unlocked_at?: string | null
          visibility?: string
        }
        Relationships: [
          {
            foreignKeyName: "capsules_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      media: {
        Row: {
          capsule_id: string
          id: string
          is_flagged: boolean
          media_type: string
          size_bytes: number
          storage_key: string
          thumbnail_key: string | null
          uploaded_at: string
          uploader_id: string | null
        }
        Insert: {
          capsule_id: string
          id?: string
          is_flagged?: boolean
          media_type: string
          size_bytes: number
          storage_key: string
          thumbnail_key?: string | null
          uploaded_at?: string
          uploader_id?: string | null
        }
        Update: {
          capsule_id?: string
          id?: string
          is_flagged?: boolean
          media_type?: string
          size_bytes?: number
          storage_key?: string
          thumbnail_key?: string | null
          uploaded_at?: string
          uploader_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "media_capsule_id_fkey"
            columns: ["capsule_id"]
            isOneToOne: false
            referencedRelation: "capsules"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "media_uploader_id_fkey"
            columns: ["uploader_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          capsule_id: string
          id: string
          pushed_at: string | null
          read_at: string | null
          sent_at: string
          type: string
          user_id: string
        }
        Insert: {
          capsule_id: string
          id?: string
          pushed_at?: string | null
          read_at?: string | null
          sent_at?: string
          type: string
          user_id: string
        }
        Update: {
          capsule_id?: string
          id?: string
          pushed_at?: string | null
          read_at?: string | null
          sent_at?: string
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_capsule_id_fkey"
            columns: ["capsule_id"]
            isOneToOne: false
            referencedRelation: "capsules"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      reactions: {
        Row: {
          created_at: string
          emoji: string
          id: string
          media_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          emoji: string
          id?: string
          media_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          emoji?: string
          id?: string
          media_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reactions_media_id_fkey"
            columns: ["media_id"]
            isOneToOne: false
            referencedRelation: "media"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      superlative_categories: {
        Row: {
          capsule_id: string
          created_at: string
          id: string
          label: string
          promoted_at: string | null
          status: string
          suggested_by: string
          target_type: string
        }
        Insert: {
          capsule_id: string
          created_at?: string
          id?: string
          label: string
          promoted_at?: string | null
          status?: string
          suggested_by: string
          target_type: string
        }
        Update: {
          capsule_id?: string
          created_at?: string
          id?: string
          label?: string
          promoted_at?: string | null
          status?: string
          suggested_by?: string
          target_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "superlative_categories_capsule_id_fkey"
            columns: ["capsule_id"]
            isOneToOne: false
            referencedRelation: "capsules"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "superlative_categories_suggested_by_fkey"
            columns: ["suggested_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      superlative_upvotes: {
        Row: {
          category_id: string
          created_at: string
          user_id: string
        }
        Insert: {
          category_id: string
          created_at?: string
          user_id: string
        }
        Update: {
          category_id?: string
          created_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "superlative_upvotes_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "superlative_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "superlative_upvotes_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      superlative_votes: {
        Row: {
          category_id: string
          created_at: string
          target_media_id: string | null
          target_user_id: string | null
          updated_at: string
          voter_id: string
        }
        Insert: {
          category_id: string
          created_at?: string
          target_media_id?: string | null
          target_user_id?: string | null
          updated_at?: string
          voter_id: string
        }
        Update: {
          category_id?: string
          created_at?: string
          target_media_id?: string | null
          target_user_id?: string | null
          updated_at?: string
          voter_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "superlative_votes_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "superlative_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "superlative_votes_target_media_id_fkey"
            columns: ["target_media_id"]
            isOneToOne: false
            referencedRelation: "media"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "superlative_votes_target_user_id_fkey"
            columns: ["target_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "superlative_votes_voter_id_fkey"
            columns: ["voter_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      superlative_winners: {
        Row: {
          category_id: string
          determined_at: string
          id: string
          target_media_id: string | null
          target_user_id: string | null
          vote_count: number
        }
        Insert: {
          category_id: string
          determined_at?: string
          id?: string
          target_media_id?: string | null
          target_user_id?: string | null
          vote_count: number
        }
        Update: {
          category_id?: string
          determined_at?: string
          id?: string
          target_media_id?: string | null
          target_user_id?: string | null
          vote_count?: number
        }
        Relationships: [
          {
            foreignKeyName: "superlative_winners_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "superlative_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "superlative_winners_target_media_id_fkey"
            columns: ["target_media_id"]
            isOneToOne: false
            referencedRelation: "media"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "superlative_winners_target_user_id_fkey"
            columns: ["target_user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          accent_color: string
          auth_provider: string
          avatar_url: string | null
          bio: string | null
          created_at: string
          display_name: string
          email: string | null
          id: string
          onboarded_at: string | null
          phone: string | null
          push_token: string | null
          subscription_tier: string
        }
        Insert: {
          accent_color?: string
          auth_provider?: string
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          display_name: string
          email?: string | null
          id: string
          onboarded_at?: string | null
          phone?: string | null
          push_token?: string | null
          subscription_tier?: string
        }
        Update: {
          accent_color?: string
          auth_provider?: string
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          display_name?: string
          email?: string | null
          id?: string
          onboarded_at?: string | null
          phone?: string | null
          push_token?: string | null
          subscription_tier?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      _haversine_m: {
        Args: { lat1: number; lat2: number; lng1: number; lng2: number }
        Returns: number
      }
      _superlative_target_valid: {
        Args: {
          p_category_id: string
          p_target_media_id: string
          p_target_user_id: string
        }
        Returns: boolean
      }
      can_insert_capsule_member: {
        Args: { p_capsule_id: string; p_user_id: string }
        Returns: boolean
      }
      check_in: {
        Args: { p_capsule_id: string; p_lat: number; p_lng: number }
        Returns: Json
      }
      close_superlative_windows: { Args: never; Returns: undefined }
      delete_my_account: {
        Args: { p_delete_contributions?: boolean }
        Returns: undefined
      }
      dispatch_superlative_closing_soon: { Args: never; Returns: undefined }
      finalize_capsule_superlatives: {
        Args: { p_capsule_id: string }
        Returns: undefined
      }
      get_my_capsule_ids: { Args: never; Returns: string[] }
      tally_superlatives: {
        Args: { p_capsule_id: string }
        Returns: {
          category_id: string
          target_media_id: string
          target_user_id: string
          vote_count: number
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
